#version: "5.0.2"

services:
  nginx:
    image: nginx:latest
    container_name: nginx-server
    restart: always
    expose:
      - 8088
    ports:
      - "80:8088"
    volumes:
      - ./onlinelib/static:/online-library/static
      - ./onlinelib/media:/online-library/media
      - ./onlinelib/logs:/online-library/logs
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - onlinelib

  onlinelib:
    image: online-library
    build:
      context: ./onlinelib
    container_name: online-library
    restart: always
    command: gunicorn -c gunicorn.py onlinelib.wsgi:application
    ports:
      - "8000:8000"
    depends_on:
      redis:
        condition: service_healthy
    environment:
      DEBUG: ${DEBUG}
      SECRET_KEY: ${SECRET_KEY}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      EMAIL_HOST_PASSWORD: ${EMAIL_HOST_PASSWORD}
    volumes:
      - ./onlinelib:/onlinelib

  redis:
    image: redis:8.6.0
    container_name: redis_cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  redis_data:

