# Generated by Django 6.0.1 on 2026-01-22 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('author', '0001_initial'),
        ('genre', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Язык')),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='Код')),
            ],
            options={
                'verbose_name': 'Язык',
                'verbose_name_plural': 'Языки',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('original_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Оригинальное название')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='slug')),
                ('cover_image', models.ImageField(default='books/covers/default.png', upload_to='books/covers/%Y/%m/%d/', verbose_name='Обложка')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('publication_year', models.IntegerField(blank=True, null=True, verbose_name='Год публикации')),
                ('upload_date', models.DateField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('views_count', models.IntegerField(default=0, verbose_name='Количество просмотров')),
                ('status', models.CharField(choices=[('available', 'Активная'), ('unavailable', 'Неактивная')], default='available', max_length=255, verbose_name='Статус')),
                ('age_rating', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='genre.agerating', verbose_name='Возрастной рейтинг')),
                ('authors', models.ManyToManyField(blank=True, related_name='books', to='author.author', verbose_name='Авторы')),
                ('genres', models.ManyToManyField(blank=True, related_name='books', to='genre.genre', verbose_name='Жанры')),
                ('post_author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to=settings.AUTH_USER_MODEL, verbose_name='Автор поста')),
                ('tags', models.ManyToManyField(blank=True, related_name='books', to='genre.tag', verbose_name='Теги')),
                ('warnings', models.ManyToManyField(blank=True, related_name='books', to='genre.contentwarning', verbose_name='Предупреждения')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_file', models.FileField(default=None, upload_to='books/files/%Y/%m/%d/', verbose_name='Файл')),
                ('upload_date', models.DateField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('download_count', models.IntegerField(default=0, verbose_name='Количество скачиваний')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='books.book', verbose_name='Книга')),
                ('post_author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to=settings.AUTH_USER_MODEL, verbose_name='Автор поста')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.language', verbose_name='Язык')),
            ],
            options={
                'verbose_name': 'Файл книги',
                'verbose_name_plural': 'Файлы книг',
            },
        ),
    ]
