# Generated by Django 5.2.8 on 2025-11-25 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('original_title', models.CharField(blank=True, max_length=255, null=True)),
                ('cover_image', models.ImageField(default='books/covers/default.png', upload_to='books/covers/%Y/%m/%d/')),
                ('description', models.TextField(blank=True, null=True)),
                ('publication_year', models.IntegerField(blank=True, null=True)),
                ('isbn', models.TextField(blank=True, null=True)),
                ('upload_date', models.DateField(auto_now_add=True)),
                ('views_count', models.IntegerField(default=0)),
                ('status', models.TextField(choices=[('available', 'Available'), ('unavailable', 'Unavailable')], default='available')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=3, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_file', models.FileField(default=None, upload_to='books/files/%Y/%m/%d/')),
                ('file_size', models.IntegerField(default=0)),
                ('upload_date', models.DateField(auto_now_add=True)),
                ('download_count', models.IntegerField(default=0)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.language')),
            ],
        ),
    ]
