# Generated by Django 5.2.8 on 2025-11-25 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('death_date', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(default='author/photos/default.png', upload_to='author/photos/%Y/%m/%d/')),
                ('bio', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
